### ISSUE TITLE
MPO(peps, i, false) does not work

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#42]
See tests logs on the kd_graphics

**Comment by bartekGardas** [comment]
Ahh, that was to be expected! Somehow, I missed that yesterday. The problem is that, when you set trace to false you get a rank 5 tensor, which is not a MPO. I'm not sure what is the best course of action here. Probably the simplest would be to make an additional structure that allows for tensors of rank 5.

**Comment by kdomino** [comment]
In my opinion, we should have such a structure and the operation that sets or traces spin's index on chosen elements of the structure.

**Comment by bartekGardas** [comment]
Defiantly, the question is rather how to incorporate it in the cleanest way possible.
