### ISSUE TITLE
MPS_search.jl tests

### ISSUE THREAD

**Issue by lpawela** [euro-hpc-pl/SpinGlassPEPS.jl#68]
Tests in this file in the current form are done by copying code from functions like `_apply_bias!`. This should not be the case. There should be a precomputed expected output of the function, which should be compared to the actual output.

**Comment by bartekGardas** [comment]
Well, functions like the one mentioned act on MPS, whereas the similar code in the test file builds tensor explicitly. This by itself is a good test. That said, some simplifications would not hurt...

**Comment by dexter2206** [comment]
I agree with @lpawela that the testing code should not copy the code from the methods under test. Otherwise, if the former is broken, the latter is broken as well and yet the test will pass.
As a side note, those tests are not very descriptive and don't illustrate the usage of the mentioned functions (i.e. if I didn't know what `_apply_bias!` does I still wouldn't know what it does after reading through tests).

**Comment by bartekGardas** [comment]
Change it to whatever you want it to be then.

**Comment by bartekGardas** [comment]
BTW: Which parts of the code are copied exactly from their underlying functions?
